[package]
name = "automl_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smartcore = "0.2.1"
automl = "0.2.6"
ndarray = "0.15.4"
ndarray-npy = "0.8.1"
rand = "0.8.5"
rand_distr = "0.4.3"